[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "v4.0.0"

[[constraint]]
  name = "k8s.io/apimachinery"
  branch = "release-1.7"

[[constraint]]
  name = "k8s.io/apiserver"
  branch = "release-1.7"

#[[constraint]]
#  name = "k8s.io/kubernetes"
#  branch = "release-1.7"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"
