[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.2"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.12.4"

[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.12.4"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.12.4"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true
