apiVersion: batch/v1
kind: Job
metadata:
  name: twister-sample
  namespace: handbrk8s
  labels:
      jobgroup: handbrake
spec:
  template:
    metadata:
      name: handbrake-twister-sample
    spec:
      containers:
      - name: handbrake
        image: carolynvs/handbrakecli:latest
        imagePullPolicy: Always
        command: ["/usr/bin/HandBrakeCLI"]
        args:
        - "--preset-import-file"
        - "/config/ghb/presets.json"
        - "-i"
        - "/watch/twister-sample.mkv"
        - "-o"
        - "/watch/twister-sample.done.mkv"
        - "--preset"
        - "tivo"
        volumeMounts:
        - mountPath: /watch
          name: mlp
      nodeSelector:
        samba: "yes"
      # Do not restart containers after they exit
      restartPolicy: Never #OnFailure
      volumes:
      - name: mlp
        hostPath:
          path: /mlp/movies/raw