apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: watcher
  namespace: handbrk8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - name: watcher
        image: carolynvs/handbrk8s-watcher:latest
        imagePullPolicy: Always
        args:
        - "--plex-server"
        - "192.168.0.103:32400"
        - "--plex-library"
        - "Movies"
        - "--plex-share"
        - "/plex/Movies"
        env:
        - name: PLEX_TOKEN
          value: "Bpfj5wDaJGqcTBqDT8wJ"
        volumeMounts:
        - mountPath: /watch
          name: mlp
      nodeSelector:
        samba: "yes"
      volumes:
      - name: mlp
        hostPath:
          path: /mlp/movies
