apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: watcher
  namespace: handbrk8s
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: watcher
    spec:
      containers:
      - name: watcher
        image: carolynvs/handbrk8s-watcher:latest
        imagePullPolicy: Always
        args:
        - "--plex-server"
        - "http://deathstar:32400"
        - "--plex-library"
        - "Movies"
        - "--plex-share"
        - "/plex/movies"
        env:
        - name: PLEX_TOKEN
          value: "Bpfj5wDaJGqcTBqDT8wJ"
        volumeMounts:
        - mountPath: /watch
          name: ponyshare
        - mountPath: /work
          name: ponyshare
      nodeSelector:
        ponyshare: ""
      volumes:
      #- name: cluster-movies
      #  persistentVolumeClaim:
      #    claimName: cluster-movies
      - name: ponyshare
        hostPath:
          path: /ponyshare
