apiVersion: v1
kind: PersistentVolume
metadata:
  name: cluster-movies
  # volumes are global, and are not namespaced
spec:
  capacity:
    storage: 500Gi
  accessModes:
  - ReadWriteMany
  nfs:
    server: ponyshare
    path: "/ponyshare/movies"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: cluster-movies
  namespace: handbrk8s
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Gi
